services:
  - type: web
    name: pickup-query-app
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install --omit=dev
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 8787
